name: flutter_lite_camera
description: "A lightweight Flutter plugin for capturing 640x480 RGB camera frames on Windows, Linux, and macOS. Ideal for previews and image processing."
version: 0.0.2
homepage: https://github.com/yushulx/flutter_lite_camera
repository: https://github.com/yushulx/flutter_lite_camera

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterLiteCameraPlugin
      macos:
        pluginClass: FlutterLiteCameraPlugin
      windows:
        pluginClass: FlutterLiteCameraPluginCApi

